# Generated by Django 3.0.2 on 2020-03-11 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Fashion', '0002_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='category',
            field=models.IntegerField(default=0),
        ),
    ]
